# Generated by Django 5.2.4 on 2025-07-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitialInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vieweeName', models.CharField(max_length=100)),
                ('vieweeInfo', models.CharField(max_length=600)),
                ('resume', models.FileField(upload_to='uploads/')),
                ('position', models.CharField(max_length=100)),
                ('context', models.CharField(max_length=600)),
            ],
        ),
    ]
